### ISSUE TITLE
Inconsistent track_ref behavior when there are no tracks

### ISSUE THREAD

**Issue by samkohn** [samkohn/larpix-reconstruction#11]
http://docs.h5py.org/en/latest/refs.html

There are 2 different behaviors for "no referenced tracks." One is to leave the HDF5 regionref uninitialized (preferred), which happens when there is a hit which is not part of any tracks. The other behavior is to set the regionref to point to something like ``tracks[0:0]`` (i.e. an empty array).

Turns out it's very easy to test for the former since ``bool(<uninitialized ref>) == False``. But it's impossible to test for the latter without using try/catch.

The specification for uninitialized references is at the bottom of the [relevant h5py page](http://docs.h5py.org/en/latest/refs.html).

**Comment by samkohn** [comment]
There is also some inconsistent behavior within h5py itself with regionrefs which I might submit a bug report about.

**Comment by peter-madigan** [comment]
This should be pretty simple to implement. I'll let you know when it's done.

**Comment by peter-madigan** [comment]
Fixed in 52e071521456640f24f20cda9b8447124cbc3360.
All empty regionrefs are left uninitialized.
